### ISSUE TITLE
Backport upstream ssl_context

### ISSUE THREAD

**Issue by hellysmile** [wikibusiness/aioelasticsearch#41]
https://github.com/elastic/elasticsearch-py/pull/635

**Comment by roganov** [comment]
`AIOHttpConnection` already accepts `ssl_context` parameter so I'm not sure what to be done here. As for `verify_certs`, `ca_certs` and `ssl_version`, they are being deprecated upstream.
@hellysmile comments?

**Comment by hellysmile** [comment]
Seems no need
